version: '3'

services:
  db:
    container_name: db
    image: postgres:15.2
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${BD_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
