version: '3'

services:
   db:
      container_name: db
      image: postgres:15.2
      restart: always
      ports:
         - ${DB_PORT}:5432
      networks:
         - control_network

   # api:
   #    stdin_open: true
   #    container_name: api
   #    image: node:18.15.0
   #    build:
   #       context: .
   #    restart: always
   #    ports:
   #       - ${SERVER_PORT}:${SERVER_PORT}
   #    working_dir: /usr/src/app
   #    volumes:
   #       - .:/usr/src/app
   #    networks:
   #       - control_network
   #    depends_on:
   #       - db
   #    command: yarn start

networks:
   control_network:
      driver: bridge

